models/Doctor.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "doctor".
 *
 * @property integer $id
 * @property string $name
 * @property string $body
 * @property integer $date_create
 * @property integer $count
 * @property string $alias
 * @property integer $weight
 * @property integer $user_id
 *
 * @property Address $address
 * @property Services $services
 * @property User $user
 * @property DoctorSpecialization[] $doctorSpecializations
 */
class Doctor extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public $imageFile;
    public $services_array;

    public function behaviors() {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }

    public static function tableName() {
        return 'doctor';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['name', 'date_create', 'count', 'alias', 'weight', 'user_id'], 'required'],
            [['body'], 'string'],
            [['services_array'], 'safe'],
            [['imageFile'], 'file', 'extensions' => 'png, jpg'],
            [['date_create', 'count', 'weight', 'user_id'], 'integer'],
            [['name', 'alias'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => '№',
            'name' => 'Имя',
            'imageFile' => 'Изображение',
            'body' => 'Описание',
            'date_create' => 'Дата создания',
            'count' => 'Просмотры',
            'alias' => 'Path',
            'services_array' => 'Услуги',
            'weight' => 'Вес',
            'user_id' => 'Пользователь',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAddress() {
        return $this->hasOne(Address::className(), ['id' => 'address_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    /* public function getDoctorService()
      {
      return $this->hasMany(DoctorService::className(), ['doctor_id' => 'id']);
      } */

    public function getServices() {
        return $this->hasMany(Services::className(), ['id' => 'services_id'])->viaTable('doctor_service', ['doctor_id' => 'id']);
    }

    public function getServicesId() {
        return $this->services->id;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser() {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function upload() {
        if ($this->validate()) {
            $path = 'upload/images/' . $this->imageFile->baseName . '.' . $this->imageFile->extension;
            $this->imageFile->saveAs($path);
            $this->attachImage($path);
            unlink($path);
            return true;
        } else {
            return false;
        }
    }

}

controllers/DoctorController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Doctor;
use app\models\DoctorSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Vopros;
use yii\bootstrap\Alert;

/**
 * DoctorController implements the CRUD actions for Doctor model.
 */
class DoctorController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Doctor models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DoctorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Doctor model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $modelVopros = new Vopros();
        
        if ($modelVopros->load(Yii::$app->request->post()) && $modelVopros->save()) {
            echo Alert::widget([
                'options' => [
                    'class' => 'alert-info',
                ],
                'body' => '<h1>Ваш вопрос отправлен</h1>',
            ]);
        }
        
        return $this->render('view', [
            'modelVopros' => $modelVopros,
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Doctor model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Doctor the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Doctor::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function beforeAction($action) {

        $model = new \app\models\Search();
        if ($model->load(Yii::$app->request->post())&& $model->search) {
            $q = $model->search;
            return $this->redirect(Yii::$app->urlManager->createUrl(['/site/search', 'q' => $q]));
        }
        return TRUE;
    }
}

views/doctor/_doctor.php
<?php

use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
?>
<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 doctor grid-item">
    <div class="doctor-wrap">
        <div class="imges">
            <img class="img-responsive" src="/web/<?= $model->getImage()->getPath('600x600') ?>" alt="">
        </div>
        <h3 class="title-doc"><?= Html::a($model->name, ['/doctor/view', 'id' => $model->id]) ?></h3>
        <div class="opis-doctor">
            <?php foreach ($model->services as $serviceDoc): ?>
                <p><?= $serviceDoc->name ?></p>
            <?php endforeach; ?>
        </div>
        <?= Html::a('Подробнее', ['/doctor/view', 'id' => $model->id], ['class' => 'btn btn-success btn-block']) ?>

    </div>
</div>

views/doctor/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\CategoryServices;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use app\models\Services;

$servic = new Services();

$modelServise = new CategoryServices();
$dataArray = [];

$modelServiseArray = $modelServise->getTree();

foreach ($modelServiseArray as $key => $valServCat) {
    $name = strval($modelServiseArray[$key]);
    $dataArray = ArrayHelper::merge($dataArray, array($name => $name));
    $dataArraySub = [];
    $dataArraySevs = ArrayHelper::map(Services::find()->where(['category_id' => $key])->all(), 'id', 'name');
    foreach ($dataArraySevs as $key => $dataArraySev) {
        $countDoctor = app\models\Doctor::find()->joinWith('services')->where(['services.id' => $key])->count();
        $dataArraySub = ArrayHelper::merge($dataArraySub, [$key => $dataArraySev . ' (' . $countDoctor . ')']);
    }
    $dataArray[$name] = $dataArraySub;
}



/* @var $this yii\web\View */
/* @var $model app\models\DoctorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="doctor-search">

    <?php
    $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
    ]);
    ?>
    <div class="scoreboard">
        <h3><i class="fa fa-heartbeat" aria-hidden="true"></i>  Подбор врача:</h3>
    </div><p></p>

    <?=
    $form->field($model, 'servicesId')->widget(Select2::classname(), [
        'data' => $dataArray,
        'language' => 'ru',
        'options' => [
            'placeholder' => 'Выберете услугу ...',
        ],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ])->label('Услуги')
    ?>

    <?= $form->field($model, 'name')->label('Имя врача') ?>

    <?php // $form->field($model, 'body') ?>

<?php // $form->field($model, 'date_create')  ?>

    <?php // $form->field($model, 'count')  ?>




    <?php // echo $form->field($model, 'alias') ?>

        <?php // echo $form->field($model, 'weight')  ?>

        <?php // echo $form->field($model, 'user_id') ?>

    <div class="form-group">
    <?= Html::submitButton('Подобрать', ['class' => 'btn btn-success']) ?> 
<?= Html::a('Сбросить', '/doctor', ['class' => 'btn btn-default']) ?>
    </div>

<?php ActiveForm::end(); ?>

</div>

views/doctor/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\DoctorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Врачи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-3 right-bar">
            <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>

        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-9 content-reght">
            


                <h1 class="text-center"><?= Html::encode($this->title) ?></h1>
                <div class="row">


                <?=
                ListView::widget([
                    'dataProvider' => $dataProvider,
                    'itemOptions' => ['class' => 'item'],
                    'itemView' => '_doctor',
                    'summary' => '',
                    'layout' => '<div class="row grid">{items}</div><div class="row">{pager}</div>'
                ])
                ?>
            </div>
                
                
                
        </div>
    </div>
</div>

views/doctor/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Doctor */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Врачи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <img style="float: left; margin: 20px" src="/web/<?= $model->getImage()->getPath('300x300') ?>" alt="">
        <div class="cont-doctor"><?= $model->body ?></div>
    </div>
    <div class="row">
        <h2 class="text-center green">Задать вопрос</h2>
        <?php $form = ActiveForm::begin(); ?>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <?= $form->field($modelVopros, 'name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <?= $form->field($modelVopros, 'telephone')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <?= $form->field($modelVopros, 'email')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <?= $form->field($modelVopros, 'vopros')->textarea(['rows' => 6]) ?>
        </div>

        <?= $form->field($modelVopros, 'doctor_id')->hiddenInput(['value' => $model->id])->label(FALSE) ?>

        <?= $form->field($modelVopros, 'date_create')->hiddenInput(['value' => date('U')])->label(FALSE) ?>

        <div class="form-group">
            <div class="text-center"><?= Html::submitButton('Отправить', ['class' => 'btn btn-success']) ?></div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>